arm_variant_type:  # [aarch64]
  - sbsa           # [aarch64]
c_stdlib:
- sysroot          # [linux]
- vs2017           # [win]
c_stdlib_version:
- '2.17'           # [linux and x86_64]
- '2.26'           # [linux and aarch64]